import type { PastLifeRoleFamily, SoulArchetypeId } from "@/types/soul";

export type PastLifeScenario = {
  id: string; archetypeId: SoulArchetypeId; period: string; region: string; location: string;
  occupation: string; socialClass: string; roleFamily: PastLifeRoleFamily; historicalContext: string;
  occupationPath: string; workplaceDetail: string; signatureObject: string; meetingReason: string;
  pressureSource: string; historicalTerms: string[];
};

export const pastLifeScenarios = [
  { id: "pioneer-ottoman-route", archetypeId: "pioneer", period: "16세기 중반", region: "오스만 제국의 아나톨리아 대상로", location: "두 갈래 대상로가 만나는 역참", occupation: "대상로 길잡이", socialClass: "언어와 지형 지식으로 자리를 만든 자유 실무자", roleFamily: "travel", historicalContext: "상단은 우물과 역참의 간격을 아는 길잡이에게 사람과 물자의 안전을 맡겼습니다.", occupationPath: "가족을 따라 여러 장터를 오가며 물길과 방언을 익혀 길잡이가 되었습니다.", workplaceDetail: "해 뜨기 전 모래의 결을 살피고 다음 우물까지의 거리를 정하던 길", signatureObject: "비에 번진 천 지도", meetingReason: "길을 잃은 필사본 상인을 다음 역참까지 안내한 일", pressureSource: "통행세를 더 받으려 위험한 지름길을 강요한 관리", historicalTerms: ["역참", "대상", "성문"] },
  { id: "pioneer-brazil-post", archetypeId: "pioneer", period: "20세기 중반", region: "브라질 남부의 이민자 정착촌", location: "새 농지가 시작되는 붉은 흙길", occupation: "정착촌 우편 배달원", socialClass: "여러 언어를 익혀 공동체 사이를 잇던 노동자", roleFamily: "travel", historicalContext: "멀리 떨어진 정착촌에서는 편지와 소식이 가족의 생사와 다음 이주를 결정했습니다.", occupationPath: "낯선 지역의 길을 가장 빨리 익혀 마을 사이의 편지와 약을 나르게 되었습니다.", workplaceDetail: "비가 오면 사라지는 흙길과 강을 건너는 나룻배", signatureObject: "주소가 세 언어로 적힌 우편가방", meetingReason: "주소가 지워진 편지의 주인을 함께 찾은 일", pressureSource: "수익이 없다는 이유로 외딴 마을 배달을 끊으려 한 운송소", historicalTerms: ["우편가방", "나룻배", "정착촌"] },

  { id: "chronicler-ming-letters", archetypeId: "chronicler", period: "15세기 중반", region: "명나라 강남의 수로 도시", location: "나룻배 선착장 옆 편지 가게", occupation: "편지 필사 장인", socialClass: "글을 모르는 상인과 가족을 위해 문장을 대신 적던 장인", roleFamily: "records", historicalContext: "수로 상업이 활발했지만 모든 사람이 긴 편지를 읽고 쓸 수 있었던 것은 아니었습니다.", occupationPath: "책방에서 종이를 다듬다가 손님들의 편지를 대신 읽고 적는 일을 맡게 되었습니다.", workplaceDetail: "먹을 갈아 먼 도시로 갈 편지를 베껴 쓰던 낮은 책상", signatureObject: "답장이 오지 않은 매화무늬 편지", meetingReason: "아픈 어머니에게 보낼 편지를 대신 써 달라는 부탁", pressureSource: "불리한 거래 내용을 편지에서 빼 달라고 요구한 큰 상단", historicalTerms: ["나룻배", "먹", "상단"] },
  { id: "chronicler-jeonju-letters", archetypeId: "chronicler", period: "19세기 후반", region: "조선 전주의 장시", location: "서책과 한지가 쌓인 작은 책방", occupation: "한글 편지 대필가", socialClass: "장날마다 사람들의 사연을 글로 옮기던 중인 실무자", roleFamily: "records", historicalContext: "한글 편지는 멀리 시집간 딸과 고향 가족이 마음을 전하는 중요한 통로였습니다.", occupationPath: "책방 일을 도우며 익힌 글로 장터 사람들의 편지를 대신 써주기 시작했습니다.", workplaceDetail: "한지와 먹 냄새가 배고 장날이면 사연을 기다리는 사람이 늘어서던 책상", signatureObject: "부치지 못한 쪽빛 봉투", meetingReason: "읽지 못한 답장의 뜻을 숨김없이 알려 달라는 부탁", pressureSource: "가문의 체면을 위해 한 사람의 편지를 없애려 한 집안 어른", historicalTerms: ["장시", "한지", "나루터"] },

  { id: "caretaker-andalusia-herbs", archetypeId: "caretaker", period: "14세기 중반", region: "안달루시아의 산기슭 도시", location: "공중목욕탕과 약초 시장 사이의 골목", occupation: "약초 치료사의 조수", socialClass: "여러 공동체의 생활 지식을 익힌 도시 평민", roleFamily: "care", historicalContext: "시장과 목욕탕 주변에서는 서로 다른 언어와 치료 지식이 함께 오갔습니다.", occupationPath: "가족을 돌보며 익힌 약초 지식 덕분에 치료사의 약방 일을 맡았습니다.", workplaceDetail: "말린 박하를 달이고 환자의 가족에게 복용법을 설명하던 약방", signatureObject: "향이 남은 작은 유리 약병", meetingReason: "열이 난 동생을 데리고 약방을 찾은 사람", pressureSource: "돈이 없는 환자를 돌려보내라고 요구한 약재 공급상", historicalTerms: ["약방", "성문", "목욕탕"] },
  { id: "caretaker-jeju-clinic", archetypeId: "caretaker", period: "20세기 중반", region: "제주도의 바닷가 마을", location: "포구에서 한 골목 떨어진 보건소", occupation: "보건소 보조원", socialClass: "전쟁과 이주 뒤 마을의 일상을 돌보던 실무자", roleFamily: "care", historicalContext: "의료 인력이 부족한 마을에서 보조원은 약뿐 아니라 소식과 돌봄을 함께 전했습니다.", occupationPath: "글을 읽고 자전거를 탈 줄 알아 먼 집에 약과 안내문을 전하는 일을 맡았습니다.", workplaceDetail: "소독약 냄새와 파도 소리가 함께 들리던 작은 진료실", signatureObject: "여러 번 기운 왕진 가방", meetingReason: "폭풍 뒤 돌아오지 않은 가족의 약을 대신 받으러 온 사람", pressureSource: "명단에 없는 이주민에게 약을 내주지 말라는 지시", historicalTerms: ["보건소", "자전거", "포구"] },

  { id: "artisan-italy-instruments", archetypeId: "artisan", period: "15세기 후반", region: "북이탈리아의 성곽 도시", location: "성당 뒤편 악기 공방 골목", occupation: "현악기 제작 장인", socialClass: "길드 공방에서 기술로 독립을 준비하던 장인", roleFamily: "craft", historicalContext: "악기는 예배와 축제에 쓰였고 제작자보다 주문한 가문의 이름이 더 크게 남았습니다.", occupationPath: "목공 견습 중 소리의 차이를 알아보는 귀를 인정받아 악기 공방으로 옮겼습니다.", workplaceDetail: "얇게 깎은 나무판의 울림을 귀에 대어 확인하던 공방", signatureObject: "작은 별을 새긴 현악기", meetingReason: "깨진 악기의 소리를 되돌려 달라는 연주자의 부탁", pressureSource: "완성품에 스승의 이름만 새기도록 한 길드 관행", historicalTerms: ["길드", "성당", "마차"] },
  { id: "artisan-venice-glass", archetypeId: "artisan", period: "18세기 초", region: "베네치아 인근의 석호 도시", location: "유리 공방의 열기가 번지는 운하 골목", occupation: "유리 세공 장인", socialClass: "가족 공방의 비법을 지키며 주문을 받던 장인", roleFamily: "craft", historicalContext: "유리 제작 기술은 도시의 중요한 자산이어서 장인의 이동과 비법 전수가 엄격히 관리됐습니다.", occupationPath: "가족 공방에서 불 조절과 색 배합을 익혀 작은 주문을 독자적으로 맡았습니다.", workplaceDetail: "화로의 색으로 온도를 읽고 녹은 유리를 천천히 돌리던 작업대", signatureObject: "금이 갔지만 버리지 못한 푸른 잔", meetingReason: "혼례 전에 깨진 잔을 몰래 복원해 달라는 부탁", pressureSource: "싼 재료를 쓰고 같은 품질이라고 속이라 한 공방주", historicalTerms: ["운하", "곤돌라", "공방"] },

  { id: "merchant-india-spice", archetypeId: "merchant", period: "16세기 후반", region: "인도 북서부의 교역 도시", location: "대상단 창고가 모인 향신료 시장", occupation: "향신료 중개인", socialClass: "언어와 신용으로 작은 거래를 키운 중간 상인", roleFamily: "trade", historicalContext: "장거리 거래에서는 저울의 정확성과 약속을 지킨 기록이 현금만큼 중요한 자산이었습니다.", occupationPath: "창고의 무게를 재는 일에서 시작해 여러 상단의 가격과 약속을 조율하게 되었습니다.", workplaceDetail: "향신료 자루 사이에서 저울추와 외상 장부를 대조하던 창고", signatureObject: "여러 상단의 표식이 찍힌 황동 저울추", meetingReason: "잘못 매겨진 빚을 바로잡아 달라는 젊은 상인의 요청", pressureSource: "흉작을 숨긴 채 가격을 올리자고 제안한 동업자", historicalTerms: ["대상단", "저울추", "역참"] },
  { id: "merchant-dutch-textile", archetypeId: "merchant", period: "17세기 중반", region: "네덜란드의 운하 도시", location: "강변 창고와 거래소 사이의 골목", occupation: "직물 거래 중개인", socialClass: "작은 신용 거래로 독립한 도시 상인", roleFamily: "trade", historicalContext: "직물 거래는 견본의 품질과 배의 도착 시기, 외상 약속에 따라 집안의 생계를 흔들었습니다.", occupationPath: "염색 공방의 견본을 배달하다 품질을 판별하는 눈을 인정받아 중개를 맡았습니다.", workplaceDetail: "창문빛 아래 천의 색과 운하 창고의 물량을 확인하던 방", signatureObject: "값을 고쳐 적은 직물 견본표", meetingReason: "가족 공방의 마지막 천을 제값에 팔아 달라는 부탁", pressureSource: "침수된 직물을 정상 물건처럼 넘기라 한 큰 상인", historicalTerms: ["운하", "거래소", "마차"] },

  { id: "wayfinder-baltic-harbor", archetypeId: "wayfinder", period: "15세기 초", region: "발트해 연안의 한자동맹 항구", location: "방파제 끝의 신호탑", occupation: "항구 수로 안내인", socialClass: "조수와 암초를 읽어 배의 입항을 돕던 항구 노동자", roleFamily: "travel", historicalContext: "낯선 선장은 얕은 수로를 아는 현지 안내인 없이는 안전하게 입항하기 어려웠습니다.", occupationPath: "어선 일을 도우며 외운 조수와 암초의 위치로 큰 배의 입항을 안내하게 되었습니다.", workplaceDetail: "안개 속에서 종과 깃발로 안전한 수로를 알리던 방파제", signatureObject: "귀환 약속이 새겨진 작은 나침반", meetingReason: "폭풍 뒤 항구를 찾지 못한 배를 새벽까지 이끈 일", pressureSource: "위험한 밤 입항을 요구한 선주", historicalTerms: ["부두", "방파제", "범선"] },
  { id: "wayfinder-canada-weather", archetypeId: "wayfinder", period: "20세기 중반", region: "캐나다 동부의 작은 항구", location: "안개가 잦은 해안 무선소", occupation: "기상 관측 보조원", socialClass: "어선에 날씨를 전하던 기술 실무자", roleFamily: "technology", historicalContext: "짧은 기상 전문 하나가 바다로 나간 배들의 귀환 여부를 바꾸곤 했습니다.", occupationPath: "라디오 수리를 배우다 구름 변화를 꼼꼼히 기록하는 성향을 인정받았습니다.", workplaceDetail: "풍향계와 무전기 사이에서 기압을 시간마다 기록하던 무선소", signatureObject: "전하지 못한 귀환 전문", meetingReason: "실종된 형제의 마지막 무전을 확인하러 온 사람", pressureSource: "예보가 불확실한데도 출항을 재촉한 선단주", historicalTerms: ["무전기", "자동차", "항구"] },

  { id: "scholar-qing-botany", archetypeId: "scholar", period: "18세기 중반", region: "청나라 남부의 차 산지", location: "차밭과 약초원이 맞닿은 서원", occupation: "식물 기록 필사자", socialClass: "재배 지식과 기록으로 생계를 잇던 서원 실무자", roleFamily: "study", historicalContext: "차나무의 병과 계절별 재배법은 그림과 필사본으로 전해져 지역의 생계를 좌우했습니다.", occupationPath: "약초 그림을 정확히 베끼는 솜씨를 인정받아 농가의 재배 기록을 정리했습니다.", workplaceDetail: "잎의 모양과 비가 온 날짜를 장부에 적던 창가", signatureObject: "이름 없는 농부의 관찰이 적힌 식물첩", meetingReason: "병든 차나무의 원인을 함께 찾아 달라는 농부의 부탁", pressureSource: "실패한 재배법을 농부 탓으로 돌리려 한 서원 책임자", historicalTerms: ["서원", "가마", "나룻배"] },
  { id: "scholar-scotland-school", archetypeId: "scholar", period: "18세기 말", region: "스코틀랜드 고원의 작은 마을", location: "교회 옆 한 칸짜리 학교", occupation: "마을 교사 겸 문서 해독가", socialClass: "교육과 토지 문서 대독을 함께 맡던 지역 지식인", roleFamily: "study", historicalContext: "외딴 마을의 교사는 글을 가르치는 일뿐 아니라 편지와 토지 계약을 대신 읽어주기도 했습니다.", occupationPath: "교회 문서를 읽어주다가 서로 다른 토지 증서에 같은 서명이 반복된다는 사실을 발견했습니다.", workplaceDetail: "수업이 끝난 뒤 마을 사람들의 편지와 토지 계약을 읽어주던 난롯가", signatureObject: "붉은 밀랍이 반쯤 뜯긴 편지", meetingReason: "폭풍우가 치던 밤 상속녀가 편지를 숨겨 달라고 찾아온 일", pressureSource: "실종된 상속녀가 스스로 달아났다고 증언하라며 협박한 토지 관리인", historicalTerms: ["교회", "마차", "난로"] },

  { id: "steward-joseon-water", archetypeId: "steward", period: "17세기 초", region: "조선 경상도의 장시 마을", location: "논과 장터를 잇는 공동 수로", occupation: "마을 수로 관리인", socialClass: "농가의 신뢰로 물길 순서를 맡은 공동체 실무자", roleFamily: "stewardship", historicalContext: "가뭄 때 물을 어느 논에 먼저 보낼지는 한 집의 수확과 마을 관계 전체를 흔들었습니다.", occupationPath: "비의 양과 논의 높낮이를 기억해 마을의 물길 순서를 기록하게 되었습니다.", workplaceDetail: "새벽마다 둑의 틈과 물 높이를 확인하던 흙길", signatureObject: "농가별 물 순서를 새긴 나무패", meetingReason: "자기 집 차례를 다른 농가에 양보해 달라는 부탁", pressureSource: "자기 집안 논에 먼저 물을 대라 한 마을 유력자", historicalTerms: ["장시", "가마", "나루터"] },
  { id: "steward-greece-olive", archetypeId: "steward", period: "20세기 중반", region: "그리스 섬의 올리브 마을", location: "항구 위쪽의 협동조합 창고", occupation: "올리브 협동조합 창고지기", socialClass: "전쟁 뒤 공동 재산을 다시 세운 마을 실무자", roleFamily: "stewardship", historicalContext: "수확량이 적은 해에는 식용 기름과 곡물 종자를 어떻게 나누는지가 마을의 다음해를 결정했습니다.", occupationPath: "남은 기름과 곡물 종자 수량을 정확히 기록해 창고를 맡았습니다.", workplaceDetail: "돌벽 창고에서 항아리 봉인과 배급표를 대조하던 작업대", signatureObject: "지워진 이름을 다시 적은 배급 장부", meetingReason: "명단에서 빠진 귀환 가족의 몫을 확인해 달라는 부탁", pressureSource: "다음 수확 전까지 남겨둘 공동 비축분까지 팔자고 주장한 조합 간부", historicalTerms: ["협동조합", "트럭", "항구"] },

  { id: "performer-france-puppets", archetypeId: "performer", period: "16세기 초", region: "프랑스 남부의 순회 장터", location: "성문 밖에 천막을 세운 유랑극단", occupation: "인형극 이야기꾼", socialClass: "장터를 돌며 수입을 나누던 유랑 예술인", roleFamily: "performance", historicalContext: "순회 공연은 글을 읽지 못하는 사람에게 소식과 풍자를 전하는 오락이기도 했습니다.", occupationPath: "의상을 꿰매다 목소리와 즉흥 연기를 인정받아 무대에 섰습니다.", workplaceDetail: "등잔 아래에서 인형의 끈과 다음 장터의 대사를 맞추던 천막", signatureObject: "한쪽만 웃는 나무 인형", meetingReason: "공연 속 인물이 자기 이야기와 닮았다며 찾아온 관객", pressureSource: "유력자를 풍자한 장면을 빼라고 협박한 시장 관리인", historicalTerms: ["성문", "마차", "장터"] },
  { id: "performer-shanghai-cinema", archetypeId: "performer", period: "20세기 초", region: "상하이 외곽의 극장 거리", location: "무성영화관 뒤편의 좁은 연주석", occupation: "무성영화 반주자", socialClass: "예술과 생계 사이에서 밤 공연을 이어가던 연주자", roleFamily: "performance", historicalContext: "무성영화의 감정과 속도는 화면 옆 연주자의 즉흥 반주에 크게 의존했습니다.", occupationPath: "찻집에서 연주하다 장면의 분위기를 읽는 능력으로 영화관 일을 맡았습니다.", workplaceDetail: "영사기 소음 속에서 화면을 보며 곡의 속도를 바꾸던 연주석", signatureObject: "마지막 장면이 비어 있는 악보", meetingReason: "같은 장면에서 울던 영사 기사와 음악을 다시 맞춘 일", pressureSource: "비극 장면도 가볍게 연주하라고 한 극장주", historicalTerms: ["전차", "영사기", "기차역"] },

  { id: "visionary-egypt-telegraph", archetypeId: "visionary", period: "19세기 말", region: "이집트 나일강변의 항구 도시", location: "철도역과 항구 사이의 전신국", occupation: "전신국 보조원", socialClass: "새 통신 기술로 가족을 부양하던 실무자", roleFamily: "technology", historicalContext: "짧은 전신 한 통은 선박의 출항과 멀리 있는 가족의 소식을 이전보다 빠르게 바꿨습니다.", occupationPath: "숫자와 신호를 정확히 받아 적는 능력으로 전신 기사의 보조가 되었습니다.", workplaceDetail: "금속 건반 소리를 문자로 옮기고 전선을 점검하던 방", signatureObject: "수신 시각이 두 번 고쳐진 전보", meetingReason: "도착하지 않은 가족의 전보를 확인해 달라는 부탁", pressureSource: "침수 경고를 늦춰 상선부터 출항시키려 한 항구 책임자", historicalTerms: ["전신", "철도", "증기선"] },
  { id: "visionary-finland-housing", archetypeId: "visionary", period: "20세기 초", region: "핀란드 호숫가의 목공 마을", location: "제재소 옆 공동 설계실", occupation: "목조 주택 설계 보조원", socialClass: "새로운 주거 방식을 배우던 기술 노동자", roleFamily: "technology", historicalContext: "사람이 도시로 몰리며 적은 재료로 따뜻하고 안전한 집을 짓는 설계가 중요해졌습니다.", occupationPath: "목공소에서 치수를 기록하다 공간을 효율적으로 쓰는 도면을 그려 설계실로 옮겼습니다.", workplaceDetail: "겨울 바람을 계산해 창과 벽의 위치를 고치던 설계대", signatureObject: "채택되지 못한 공동주택 도면", meetingReason: "화재로 집을 잃은 가족에게 작은 집의 도면을 보여준 일", pressureSource: "비용을 줄이려고 단열재를 빼라 한 건축업자", historicalTerms: ["기차역", "자전거", "제재소"] },
] satisfies readonly PastLifeScenario[];

export function getScenariosForArchetype(archetypeId: SoulArchetypeId): readonly PastLifeScenario[] {
  return pastLifeScenarios.filter((scenario) => scenario.archetypeId === archetypeId);
}
