import { pastLifeScenarios, type PastLifeScenario } from "./pastLifeScenarios";
import { pastLifeStoryCores, type PastLifeStoryCore } from "./pastLifeStoryCores";
import type { LifeBlueprint, LifeBlueprintValidation, ObjectRole } from "@/types/soul";
import { withAnd, withObject } from "@/lib/content/koreanGrammar";

const valid: LifeBlueprintValidation = {
  hasRelationshipReason: true,
  hasTrustReason: true,
  hasAntagonistMotive: true,
  hasNoEasyExit: true,
  hasEscalation: true,
  hasCost: true,
};

const curatedBlueprints = {
  "pioneer-ottoman-route": {
    protagonistDesire: "몇 해만 더 정기 대상의 길을 맡아 가족이 머물 작은 집을 마련하는 것",
    keyRelationship: "고향의 필사본을 되찾으러 온 젊은 상단주",
    relationshipOrigin: "첫 장거리 길에서 모래폭풍을 만났을 때, 상단주가 낙오한 짐꾼을 두고 가지 않겠다고 버티면서 함께 밤길을 찾았습니다.",
    trustReason: "그 뒤 세 차례의 여정을 함께하며 주인공이 물이 부족할 때도 약한 사람의 몫을 먼저 남기는 것을 직접 보았기 때문에 위험한 우회로의 판단을 맡겼습니다.",
    protagonistInvolvement: "이번 대상의 계약서에 길잡이로 이름을 올렸고, 길을 택할 권한과 도착하지 못했을 때 가족에게 갚아야 할 보증금이 모두 주인공에게 묶여 있었습니다.",
    antagonistMotive: "역참 관리는 새로 만든 협곡 길의 통행세를 이번 달 안에 채워야 상급 관리에게 빌린 돈과 역참 운영권을 지킬 수 있었습니다.",
    antagonistInterestInProtagonist: "다른 길잡이들이 주인공의 판단을 따랐으므로, 주인공 한 사람의 동의 없이는 누구도 유료 협곡으로 들어가지 않을 상황이었습니다.",
    noEasyExit: "출발 뒤 사흘이 지나 돌아갈 물이 부족했고, 혼자 떠나면 계약 보증금뿐 아니라 남은 대상의 길까지 잃게 되어 가족과 동료 모두가 위험해졌습니다.",
    incitingIncident: "앞서 간 염소지기가 폭우로 협곡 입구가 무너졌다고 알렸지만, 관리는 예정대로 그 길을 쓰라고 명령했습니다.",
    firstEscalation: "관리는 우회로에 도적이 나타났다는 거짓 소문을 퍼뜨리고 주인공의 물자 배급권을 빼앗았습니다.",
    midpointRevelation: "상단주는 관리가 전날 이미 붕괴 소식을 받고도 통행세 수입을 적어 보낸 영수증을 보았다고 털어놓았습니다.",
    pointOfNoReturn: "주인공은 밤중에 대상의 선두를 돌려 관리의 경비병들이 지키는 길목을 벗어났고, 그 순간 계약 위반자로 기록되었습니다.",
    climax: "동이 틀 무렵 관리의 기마 경비가 따라붙자 주인공은 좁은 마른 강바닥 대신 오래 걸리지만 물이 남은 북쪽 길로 모두를 이끌었습니다.",
    aftermath: "대상은 이틀 늦게 장터에 닿았고 사람들은 살았지만, 주인공은 역참 길잡이 명부에서 이름이 지워졌습니다.",
    actualLoss: "정기 품삯과 마련 중이던 집의 계약금",
    actualGainOrPreservedThing: "서른두 명의 목숨과 위험을 숨기지 않는 길잡이라는 신뢰",
    unspokenWords: "집을 얻는 꿈보다 당신과 같은 길을 다시 걷는 일이 더 중요해졌다고 말하지 못했습니다.",
    promise: "다음 봄에는 통행세가 아니라 안전을 기준으로 새 대상로를 함께 열기로 한 약속",
    promiseBreakReason: "주인공이 명부에서 쫓겨난 뒤 국경 밖으로 먼저 떠나면서 약속한 봄에 돌아오지 못했습니다.",
    lastVisitor: "오랜 세월 뒤 새 대상로의 표식을 들고 찾아온 그 상단주",
    finalMemory: "첫 모래폭풍 속에서 두 사람이 낙오한 짐꾼의 손을 함께 잡았던 밤",
    objectRole: "TOOL",
    dramaticHook: "무너진 협곡 앞에서, 집을 살 돈과 서른두 명의 귀환 중 하나를 골라야 했습니다.",
    decisionActions: {
      ALLY: "상단주에게 영수증 이야기를 먼저 확인하고, 물과 낙타 수를 함께 계산해 북쪽 우회 순서를 짰습니다.",
      TRUTH: "각 상단 대표에게 붕괴 소식과 관리가 이미 받은 보고를 공개했습니다. 늦어질 비용도 숨김없이 밝혔습니다.",
      COMMUNITY: "짐꾼과 상인들이 가진 물을 다시 나누고, 길을 아는 사람마다 한 구간씩 선두를 맡는 우회대를 꾸렸습니다.",
      DEFIANCE: "역참 뜰에서 무너진 길로는 누구도 이끌지 않겠다고 선언하고 관리가 내민 계약 갱신표를 찢었습니다.",
      DEPARTURE: "관리의 역참과 계약을 버리고 대상 전체를 북쪽 유목민의 물길로 옮겨 독립된 안내대를 시작했습니다.",
      RESTORATION: "관리에게 지워진 북쪽 우물과 피난 길을 다시 확인해 여러 역참의 공용 천 지도에 돌려놓았습니다.",
    },
    timeline: {
      youth: { ageRange: "9~16세", title: "길을 외운 아이", summary: "가족의 장사를 따라다니며 방언과 우물 사이의 거리를 외웠습니다.", location: "아나톨리아 장터" },
      earlyAdult: { ageRange: "17~25세", title: "이름을 건 첫 계약", summary: "낙오자를 모두 데려오는 길잡이로 알려져 정기 대상의 보증을 맡았습니다.", location: "역참" },
      keyRelationship: { ageRange: "24~31세", title: "세 번의 길", summary: "모래폭풍 속 구조를 시작으로 젊은 상단주와 세 차례 여정을 함께하며 신뢰를 쌓았습니다.", relatedPerson: "젊은 상단주" },
      centralConflict: { ageRange: "32세", title: "무너진 협곡", summary: "통행세 때문에 위험을 숨긴 관리와 맞서 대상을 북쪽 길로 돌렸습니다.", location: "협곡 앞 역참" },
      aftermath: { ageRange: "32~35세", title: "명부 밖의 길잡이", summary: "집 계약금을 잃었지만 살아 돌아온 이들과 독립 안내대를 꾸렸습니다." },
      laterLife: { ageRange: "50대", title: "물길을 가르치는 사람", summary: "젊은 길잡이에게 지도보다 현지 사람의 경고를 먼저 듣는 법을 가르쳤습니다." },
      finalYears: { ageRange: "70대", title: "다시 온 봄", summary: "상단주가 완성한 새 길의 표식을 받아 들고 첫 모래폭풍의 밤을 떠올렸습니다.", relatedPerson: "젊은 상단주" },
    },
    validation: valid,
  },
  "caretaker-jeju-clinic": {
    protagonistDesire: "전쟁 뒤 흩어진 동생들을 한집으로 불러 조용한 생활을 다시 만드는 것",
    keyRelationship: "포구의 누락된 환자를 함께 찾아다닌 젊은 의사",
    relationshipOrigin: "폭풍 다음 날 의사가 길을 몰라 헤매자 주인공이 자전거 뒤에 약 상자를 싣고 포구의 집들을 안내했습니다.",
    trustReason: "의사는 주인공이 주민의 사정을 함부로 떠벌리지 않으면서도 복용 시간과 알레르기를 정확히 기억하는 모습을 여러 달 지켜보았습니다.",
    protagonistInvolvement: "누락된 가족은 주인공의 빈방에 머물던 피란민이었고, 처방약을 전하지 않으면 어린 환자의 열이 다시 오를 가능성이 컸습니다.",
    antagonistMotive: "면사무소 책임자는 배급 인원을 줄였다는 실적으로 중앙의 감사를 피하고, 부족한 약품 수량을 숨기려 했습니다.",
    antagonistInterestInProtagonist: "실제 왕진 명단과 포구 사람들의 거처를 동시에 아는 사람이 주인공뿐이라 누락을 입증하거나 감출 수 있었습니다.",
    noEasyExit: "직장을 그만두어도 환자는 그날 약을 받지 못하고, 피란민을 숨겨 준 사실이 드러나면 동생들을 데려올 집까지 빼앗길 수 있었습니다.",
    incitingIncident: "의사가 처방한 아이의 이름이 새 배급 명단에서 사라져 약 창고가 문을 열어주지 않았습니다.",
    firstEscalation: "책임자는 누락을 말하는 주민에게는 다음 달 식량표도 내주지 않겠다고 경고했습니다.",
    midpointRevelation: "주인공은 명단의 다른 이름들도 같은 날 한꺼번에 지워졌고 그 수가 사라진 약 상자 수와 일치한다는 사실을 알았습니다.",
    pointOfNoReturn: "주인공은 창고 열쇠를 사용해 처방된 양만 꺼내 의사와 함께 포구로 향했고, 장부에는 자신의 이름을 남겼습니다.",
    climax: "책임자가 길을 막자 주민들은 각자의 진료 쪽지를 들고 보건소 앞에 모였고, 의사는 실제 환자 수를 공개했습니다.",
    aftermath: "누락 명단은 다시 작성되었지만 주인공은 보건소 자리와 관사 배정을 잃고 포구의 빈집에서 왕진 연락을 맡았습니다.",
    actualLoss: "정기 급료와 동생들과 살 예정이던 관사",
    actualGainOrPreservedThing: "아이의 치료와 이름이 지워진 주민들이 의료를 받을 자격",
    unspokenWords: "당신과 함께라면 잃어버린 가족의 자리를 다시 만들 수 있을 것 같다고 말하지 못했습니다.",
    promise: "폭풍이 지나도 명단 밖 사람을 먼저 찾아가는 왕진 길을 함께 지키겠다는 약속",
    promiseBreakReason: "의사가 섬 밖 병원으로 징계를 받아 떠나며 둘이 함께 돌던 길은 오래 이어지지 못했습니다.",
    lastVisitor: "성인이 되어 보건원이 된 그때의 어린 환자",
    finalMemory: "자전거가 진흙에 빠졌을 때 의사와 함께 웃으며 약 상자를 들고 걸었던 오후",
    objectRole: "MEMORY",
    dramaticHook: "명단에서 사라진 아이에게 약을 건네는 순간, 주인공의 집과 직장도 함께 사라질 수 있었습니다.",
    decisionActions: {
      ALLY: "젊은 의사에게 누락된 집들의 위치를 먼저 알리고, 처방과 남은 약 수량을 맞춰 둘이 왕진 순서를 정했습니다.",
      TRUTH: "보건소 앞에서 실제 환자 수와 사라진 약 상자 수를 주민들에게 설명하고 자신의 창고 출입 기록도 공개했습니다.",
      COMMUNITY: "포구 주민들과 집마다 남은 약과 식량표를 확인해 누락 환자 명부를 만들고 의사가 처방을 재확인하게 했습니다.",
      DEFIANCE: "책임자 앞에서 처방받은 사람을 명단 때문에 돌려보내지 않겠다고 말하고 창고 열쇠를 반납했습니다.",
      DEPARTURE: "보건소 관사를 포기하고 의사와 포구의 빈집을 왕진 연락소로 바꾸어 명단 밖 환자를 직접 찾아갔습니다.",
      RESTORATION: "왕진 기록과 주민 확인을 모아 지워진 이름을 공식 환자 명부에 되돌리고 각자의 처방약을 전달했습니다.",
    },
    timeline: {
      youth: { ageRange: "10~17세", title: "흩어진 가족", summary: "전쟁과 이주 속에서 어린 동생들을 돌보며 글을 익혔습니다.", location: "제주 바닷가" },
      earlyAdult: { ageRange: "18~27세", title: "자전거 왕진", summary: "길과 집을 잘 안다는 이유로 보건소 약과 안내문을 배달했습니다.", location: "포구 보건소" },
      keyRelationship: { ageRange: "25~33세", title: "함께 걷던 왕진 길", summary: "젊은 의사와 폭풍 뒤 환자를 찾으며 서로의 정확함과 침묵을 믿게 됐습니다.", relatedPerson: "젊은 의사" },
      centralConflict: { ageRange: "34세", title: "지워진 이름", summary: "약품 부족을 숨기려는 책임자에 맞서 누락된 환자들에게 처방약을 전했습니다." },
      aftermath: { ageRange: "34~39세", title: "포구의 연락소", summary: "관사를 잃고 동생들과 살 꿈은 늦어졌지만 주민들과 왕진 연락소를 만들었습니다." },
      laterLife: { ageRange: "50~60대", title: "이름을 먼저 묻는 사람", summary: "새 보건원들에게 명단보다 환자의 이름과 사정을 먼저 확인하게 했습니다." },
      finalYears: { ageRange: "70대", title: "돌아온 왕진 가방", summary: "옛 어린 환자가 기운 왕진 가방을 들고 찾아와 새 보건원이 되었다고 전했습니다.", relatedPerson: "어린 환자" },
    },
    validation: valid,
  },
  "artisan-venice-glass": {
    protagonistDesire: "가족 공방 안에서 자신의 작은 화로와 이름을 건 주문을 얻는 것",
    keyRelationship: "혼례용 푸른 잔을 주문한 직물상 집안의 하녀",
    relationshipOrigin: "하녀가 주인집에서 깨뜨린 오래된 잔을 들고 왔고, 주인공은 벌을 피하도록 흔적을 감추는 대신 정직하게 수리 방법을 알려주었습니다.",
    trustReason: "하녀는 주인공이 자기 실수를 이용해 값을 올리지 않았고, 수리가 어렵다는 사실까지 먼저 말해 준 일을 기억해 혼례 주문의 균열도 보여주었습니다.",
    protagonistInvolvement: "혼례 잔의 마지막 열처리를 주인공 이름으로 맡았기에 불량품이 깨지면 하녀가 아니라 주인공과 어린 견습생이 책임을 져야 했습니다.",
    antagonistMotive: "공방주는 큰 혼례 주문의 선금을 빚 상환에 이미 써버려, 좋은 재료를 다시 사면 공방 소유권을 채권자에게 넘겨야 했습니다.",
    antagonistInterestInProtagonist: "화로 온도와 배합을 실제로 맡은 주인공만 완성품에 안전 표시를 새길 수 있어 침묵시키지 않으면 납품이 불가능했습니다.",
    noEasyExit: "도시의 장인 이동 제한 때문에 공방을 나가면 다른 화로를 쓸 수 없었고, 남으면 자신의 표시로 위험한 잔을 보증해야 했습니다.",
    incitingIncident: "식힌 푸른 잔 하나에 가느다란 금이 생겼고 같은 배합의 잔들에서도 낮은 울림이 났습니다.",
    firstEscalation: "공방주는 금 간 잔을 버리고 아무 표시 없이 납품하라고 하며 어린 견습생에게 배합 실수의 책임을 씌웠습니다.",
    midpointRevelation: "하녀는 공방주가 선금을 되돌릴 수 없다는 말을 채권자와 나누는 것을 들었고, 혼례 뒤 잔을 외국 상단에도 팔 계획임을 알려주었습니다.",
    pointOfNoReturn: "주인공은 완성된 상자마다 안전 표시 대신 균열 가능성을 뜻하는 자신의 작은 흠집을 남겨 주문자가 알아보게 했습니다.",
    climax: "납품 전 검사 자리에서 주인공은 잔 하나를 뜨거운 물에 넣어 스스로 갈라지는 모습을 보이고 재제작을 요구했습니다.",
    aftermath: "혼례 주문은 절반만 다시 만들어졌고 공방은 채권자에게 넘어갔습니다. 주인공은 화로를 잃었지만 하녀와 동료의 도움으로 작은 수리 작업대를 얻었습니다.",
    actualLoss: "가족 공방의 화로와 독립 장인이 될 예정이던 자리",
    actualGainOrPreservedThing: "견습생의 누명과 잔을 사용할 사람들의 안전, 자기 이름으로 보증할 기준",
    unspokenWords: "당신이 내 물건보다 내 판단을 먼저 믿어준 첫 사람이었다고 말하지 못했습니다.",
    promise: "하녀가 자기 이름으로 살림을 시작하는 날 깨지지 않는 푸른 잔 둘을 만들어 주겠다는 약속",
    promiseBreakReason: "공방을 잃으며 같은 푸른색을 내는 재료를 구하지 못해 약속한 날 잔을 완성하지 못했습니다.",
    lastVisitor: "오래전 하녀였던 직물 가게 주인",
    finalMemory: "수리할 수 없다는 정직한 답을 듣고도 하녀가 안도하듯 웃었던 첫날",
    objectRole: "SYMBOL",
    dramaticHook: "혼례 잔의 균열을 숨기면 화로를 지킬 수 있었지만, 그 잔에는 주인공의 이름이 걸려 있었습니다.",
    decisionActions: {
      ALLY: "하녀와 견습생에게 균열의 원인을 먼저 설명하고, 주문자가 직접 확인할 검사 자리를 함께 마련했습니다.",
      TRUTH: "납품 명세에 재료 변경과 균열 가능성을 적고 혼례 집안과 동료 장인들에게 같은 내용을 알렸습니다.",
      COMMUNITY: "동료 장인들과 좋은 재료와 화로 시간을 나누어 주문 수량을 줄인 안전한 잔을 다시 만들었습니다.",
      DEFIANCE: "공방의 주문 검사 자리에서 불량 유리에 자기 표식을 새길 수 없다고 선언하고 화로 열쇠를 내려놓았습니다.",
      DEPARTURE: "가족 공방을 나와 하녀와 수리 의뢰를 모으고, 동료의 밤 화로를 빌려 작은 작업대를 시작했습니다.",
      RESTORATION: "견습생에게 씌운 배합 실수를 바로잡고 이미 포장된 잔을 회수해 주문자의 안전한 잔 수량을 되돌렸습니다.",
    },
    timeline: {
      youth: { ageRange: "8~15세", title: "화로 곁의 아이", summary: "가족 공방에서 재와 모래를 치우며 불의 색을 읽었습니다.", location: "석호 도시의 공방" },
      earlyAdult: { ageRange: "16~27세", title: "이름 없는 솜씨", summary: "작은 주문을 맡았지만 완성품에는 늘 공방주의 이름만 남았습니다." },
      keyRelationship: { ageRange: "24~31세", title: "깨진 잔의 방문", summary: "수리를 맡긴 하녀에게 불가능한 것은 불가능하다고 말한 뒤 오랜 신뢰가 시작됐습니다.", relatedPerson: "직물상 집안의 하녀" },
      centralConflict: { ageRange: "32세", title: "푸른 잔의 균열", summary: "빚 때문에 불량 잔을 납품하려는 공방주에게 공개 검사로 맞섰습니다." },
      aftermath: { ageRange: "32~38세", title: "화로 없는 장인", summary: "가족 화로를 잃었지만 수리 작업대에서 자기 이름으로 받을 주문을 시작했습니다." },
      laterLife: { ageRange: "50대", title: "두 개씩 만드는 습관", summary: "견습생에게 시험용 한 개를 먼저 깨뜨려 본 뒤 주문품을 만들게 했습니다." },
      finalYears: { ageRange: "60대 후반", title: "다른 빛의 푸른 잔", summary: "옛 하녀가 찾아오자 완벽히 같은 색은 아니지만 오래 견딘 푸른 잔을 함께 마주했습니다.", relatedPerson: "직물 가게 주인" },
    },
    validation: valid,
  },
  "scholar-scotland-school": {
    protagonistDesire: "작은 학교와 난롯가 방을 지키며 마을 아이들을 계속 가르치는 것",
    keyRelationship: "저택의 장부를 직접 익히던 상속녀",
    relationshipOrigin: "상속녀가 소작 계약을 스스로 읽고 싶다며 수업이 끝난 학교를 반년 동안 찾아오면서 서로 알게 됐습니다.",
    trustReason: "주인공은 그녀가 틀리게 읽은 문서를 대신 결정하지 않고 뜻과 결과를 설명해 스스로 판단하게 했고, 이전 계약의 위조도 먼저 알려주었습니다.",
    protagonistInvolvement: "주인공은 토지 계약을 대독한 증인이자 상속녀의 공부를 아는 유일한 마을 사람이어서, 그녀가 자발적으로 떠났다는 주장에 반박할 수 있었습니다.",
    antagonistMotive: "토지 관리인은 상속녀가 성년이 되기 전에 자기 조카와 혼인시키면 저택의 빚과 넓은 방목지를 한꺼번에 넘겨받을 수 있었습니다.",
    antagonistInterestInProtagonist: "주인공이 같은 필체가 반복된 증서와 상속녀의 실제 의사를 모두 알고 있어 거짓 도피 이야기를 무너뜨릴 수 있었습니다.",
    noEasyExit: "침묵하면 학교와 집은 지킬 수 있지만 상속녀는 사흘 뒤 강제 혼인을 하게 되고, 떠나면 관리인이 마을의 소작 계약까지 바꿀 수 있었습니다.",
    incitingIncident: "폭풍우가 치던 밤 상속녀가 사흘 뒤 원치 않는 혼인을 해야 한다며 도움을 청한 뒤 저택으로 돌아갔습니다.",
    firstEscalation: "다음 날 그녀가 사라졌고 관리인은 주인공에게 원래 도시로 달아날 계획이었다고 증언하라고 요구했습니다.",
    midpointRevelation: "여관 주인은 관리인의 마차가 밤중에 사냥 별장 쪽으로 갔다고 말했고, 주인공은 혼인이 아니라 감금이 먼저 계획됐음을 깨달았습니다.",
    pointOfNoReturn: "주인공은 예배 뒤 마을 사람들 앞에서 거짓 증언 요구를 밝혔고 관리인은 즉시 학교 문을 봉했습니다.",
    climax: "대장장이와 여관 주인이 별장의 길을 막는 동안 주인공은 상속녀를 데리고 교구 책임자 앞에서 자신의 의사를 직접 말하게 했습니다.",
    aftermath: "강제 혼인은 멈췄지만 소송은 오래 이어졌고, 주인공은 학교와 집을 잃은 채 다른 마을에서 문서 읽는 법을 가르쳤습니다.",
    actualLoss: "교사 자리와 학교에 붙어 있던 살림방",
    actualGainOrPreservedThing: "상속녀가 혼인과 재산을 스스로 결정할 권리와 마을 사람들이 계약을 확인하는 습관",
    unspokenWords: "당신이 떠난 뒤에도 학교를 지키려 했던 것은 그곳에서 함께 읽던 저녁을 잃고 싶지 않았기 때문이라고 말하지 못했습니다.",
    promise: "소송이 끝나면 누구나 계약을 읽을 수 있는 방을 옛 학교에 함께 만들겠다는 약속",
    promiseBreakReason: "소송이 끝나기 전 주인공이 다른 마을로 추방되어 둘은 약속한 방을 함께 열지 못했습니다.",
    lastVisitor: "문서 읽는 방의 첫 열쇠를 들고 온 상속녀",
    finalMemory: "상속녀가 처음으로 계약의 뜻을 자기 말로 설명하고 난롯가에서 웃었던 저녁",
    objectRole: "MACGUFFIN",
    dramaticHook: "상속녀가 사라진 다음 날, 그녀의 선택을 아는 유일한 증인에게 거짓말할 집과 침묵할 학교가 제시됐습니다.",
    decisionActions: {
      ALLY: "상속녀의 행방을 아는 여관 주인과 먼저 움직여 별장 뒷길을 확인하고, 그녀가 직접 말할 수 있는 자리를 준비했습니다.",
      TRUTH: "교구 책임자에게 위조 증서의 필체와 거짓 도피 증언 요구를 설명하고 상속녀의 실제 의사를 기록하게 했습니다.",
      COMMUNITY: "대장장이와 여관 주인, 소작농들이 별장 길과 교회 입구를 나누어 지키며 상속녀가 안전하게 증언하도록 했습니다.",
      DEFIANCE: "예배 뒤 마을과 교구 관계자가 모인 자리에서 관리인의 거짓 증언 요구를 밝히고 학교 열쇠를 돌려주었습니다.",
      DEPARTURE: "봉인된 학교를 떠나 상속녀와 에든버러로 가서 감금 사실과 강제 혼인, 위조 계약을 직접 다투었습니다.",
      RESTORATION: "마을 사람들이 보관한 계약 사본을 대조해 바뀐 소작 조건과 상속녀의 권리를 원래 문서에 되돌렸습니다.",
    },
    timeline: {
      youth: { ageRange: "7~16세", title: "빌린 책의 아이", summary: "목사의 책을 베껴 읽으며 겨울마다 어린아이들에게 글자를 가르쳤습니다.", location: "고원 마을" },
      earlyAdult: { ageRange: "17~29세", title: "난롯가의 교사", summary: "교회 옆 학교를 맡고 저녁에는 주민의 편지와 계약을 읽어주었습니다." },
      keyRelationship: { ageRange: "27~34세", title: "수업이 끝난 뒤", summary: "상속녀가 반년 동안 계약 읽는 법을 배우며 둘 사이에 판단을 맡길 신뢰가 생겼습니다.", relatedPerson: "저택의 상속녀" },
      centralConflict: { ageRange: "35세", title: "봉인된 학교", summary: "강제 혼인과 감금을 밝힌 대가로 학교를 잃고 상속녀의 증언을 지켰습니다." },
      aftermath: { ageRange: "35~42세", title: "떠도는 수업", summary: "다른 마을의 부엌과 마구간을 빌려 주민들에게 계약을 읽는 법을 가르쳤습니다." },
      laterLife: { ageRange: "50~60대", title: "이름을 쓰는 마을", summary: "가르친 사람들이 자기 계약에 직접 이름을 쓰는 모습을 보며 작은 학교들을 이어갔습니다." },
      finalYears: { ageRange: "70대", title: "늦게 온 열쇠", summary: "상속녀가 옛 학교에 연 문서 읽는 방의 열쇠를 건넸고, 둘은 약속이 다른 모습으로 이루어졌음을 알았습니다.", relatedPerson: "저택의 상속녀" },
    },
    validation: valid,
  },
  "performer-shanghai-cinema": {
    protagonistDesire: "밤 공연 수입을 모아 어머니와 함께 살 작은 찻집을 여는 것",
    keyRelationship: "화면의 호흡을 함께 맞추던 영사 기사",
    relationshipOrigin: "필름이 끊긴 첫 공연에서 영사 기사가 손전등으로 박자를 보내고 주인공이 즉흥곡으로 빈 시간을 메우며 가까워졌습니다.",
    trustReason: "두 사람은 수백 번의 상영에서 실수와 관객 반응을 숨기지 않고 서로 알려주었고, 영사 기사는 주인공이 필름보다 사람을 탓하지 않는 것을 믿었습니다.",
    protagonistInvolvement: "잘린 장면의 음악은 주인공만 기억했고, 관객에게 이미 다음 자선 상영의 수익을 유가족에게 보내겠다고 약속한 상태였습니다.",
    antagonistMotive: "극장주는 하루 상영 횟수를 한 차례 늘려 밀린 필름 대여료를 갚고 경쟁 극장에 관객을 빼앗기지 않으려 했습니다.",
    antagonistInterestInProtagonist: "관객들이 주인공의 느린 마지막 곡을 영화의 일부로 기억해, 반주자가 따르지 않으면 장면 삭제를 눈치챌 가능성이 컸습니다.",
    noEasyExit: "그만두면 찻집 자금과 어머니의 약값을 잃고 자선 상영 약속도 깨지며, 남아 침묵하면 영사 기사에게 삭제 책임이 돌아갔습니다.",
    incitingIncident: "새 필름에서 사고 희생자를 애도하는 마지막 장면이 잘려 나가고 악보의 해당 장도 사라졌습니다.",
    firstEscalation: "극장주는 영사 기사가 필름을 훼손했다고 소문내며 손해 전액을 그의 급료에서 빼겠다고 했습니다.",
    midpointRevelation: "매표원이 하루 한 차례를 더 상영하라는 새 시간표를 보여주면서 삭제가 사고가 아니라 회전율을 위한 지시였음이 드러났습니다.",
    pointOfNoReturn: "주인공은 만원 관객 앞에서 잘린 시간만큼 연주를 멈추고, 무엇이 사라졌는지 설명했습니다.",
    climax: "영사 기사가 보관한 원본 장면을 비추자 주인공은 기억한 느린 곡을 연주했고 관객들은 환불 대신 약속한 자선함에 표를 넣었습니다.",
    aftermath: "두 사람은 해고됐고 찻집 계획은 미뤄졌지만, 작은 찻집들을 돌며 영화와 음악을 함께 보여주는 밤 공연을 시작했습니다.",
    actualLoss: "극장 전속 수입과 어머니와 열려던 찻집의 보증금",
    actualGainOrPreservedThing: "영사 기사의 누명과 희생자를 기억할 관객의 마지막 장면",
    unspokenWords: "무대가 아니라 당신과 같은 침묵을 듣는 시간이 좋아서 남았다고 말하지 못했습니다.",
    promise: "돈이 모이면 둘만의 작은 상영실에서 어떤 결말도 자르지 않겠다는 약속",
    promiseBreakReason: "순회 공연 수입이 가족의 치료비로 쓰여 둘만의 상영실을 열 만큼 돈이 모이지 않았습니다.",
    lastVisitor: "낡은 영사 손잡이를 들고 온 옛 영사 기사",
    finalMemory: "끊긴 필름 앞에서 손전등 박자와 즉흥 피아노가 처음 맞았던 공연",
    objectRole: "LOSS",
    dramaticHook: "잘린 마지막 장면을 되살리면 어머니의 약값을 잃고, 침묵하면 가장 믿는 사람이 누명을 썼습니다.",
    decisionActions: {
      ALLY: "영사 기사와 잘린 길이와 기억한 박자를 먼저 맞추고, 원본 장면을 안전하게 상영할 순서를 짰습니다.",
      TRUTH: "상영을 멈춘 시간에 관객에게 삭제된 장면과 늘어난 회차를 설명하고 매표 시간표를 공개했습니다.",
      COMMUNITY: "연주자와 매표원, 찻집 주인들이 장면과 음악을 나누어 보관해 어느 한 사람의 해고로 상영이 사라지지 않게 했습니다.",
      DEFIANCE: "만원 관객 앞에서 비극을 희극처럼 연주하라는 요구를 거절하고 잘린 시간 동안 피아노에서 손을 뗐습니다.",
      DEPARTURE: "극장 전속 자리를 떠나 영사 기사와 찻집을 돌며 원본 영화와 새 반주를 보여주는 밤 공연을 시작했습니다.",
      RESTORATION: "영사 기사가 지킨 원본 길이에 맞춰 사라진 악보를 다시 쓰고 희생자 유가족을 위한 마지막 장면을 복원했습니다.",
    },
    timeline: {
      youth: { ageRange: "9~16세", title: "찻집의 피아노", summary: "어머니가 일하던 찻집에서 손님이 없는 시간에 피아노를 익혔습니다.", location: "상하이 외곽 찻집" },
      earlyAdult: { ageRange: "17~26세", title: "화면 옆의 연주자", summary: "장면의 표정과 관객의 숨에 맞춰 곡의 속도를 바꾸는 반주자가 됐습니다." },
      keyRelationship: { ageRange: "23~31세", title: "손전등의 박자", summary: "필름 사고를 함께 넘긴 뒤 영사 기사와 말보다 신호를 먼저 믿는 사이가 됐습니다.", relatedPerson: "영사 기사" },
      centralConflict: { ageRange: "32세", title: "잘린 결말", summary: "상영 횟수를 늘리려 지운 마지막 장면을 관객 앞에서 원래 음악과 함께 되살렸습니다." },
      aftermath: { ageRange: "32~40세", title: "찻집 순회 상영", summary: "전속 자리와 보증금을 잃고도 작은 찻집에서 관객과 가까운 공연을 이어갔습니다." },
      laterLife: { ageRange: "50대", title: "장면을 맡기는 선생", summary: "젊은 연주자들에게 화면보다 관객이 숨을 고르는 시간을 먼저 들으라고 가르쳤습니다." },
      finalYears: { ageRange: "60대", title: "마지막 무성 상영", summary: "옛 영사 기사와 작은 벽에 첫 사고 영화를 비추며 손전등 박자를 다시 맞췄습니다.", relatedPerson: "영사 기사" },
    },
    validation: valid,
  },
} satisfies Record<string, LifeBlueprint>;

const objectRoles: ObjectRole[] = ["MEMORY", "SYMBOL", "TOOL", "LOSS", "MACGUFFIN"];

const migratedBlueprints = Object.fromEntries(
  pastLifeScenarios
    .filter((scenario) => !(scenario.id in curatedBlueprints))
    .map((scenario, index) => [scenario.id, migrateStoryCore(scenario, pastLifeStoryCores[scenario.id], objectRoles[index % objectRoles.length])]),
) as Record<string, LifeBlueprint>;

export const pastLifeBlueprints: Record<string, LifeBlueprint> = {
  ...migratedBlueprints,
  ...curatedBlueprints,
};

function migrateStoryCore(scenario: PastLifeScenario, core: PastLifeStoryCore, objectRole: ObjectRole): LifeBlueprint {
  const consequenceSentences = core.consequence.split(". ");
  const lossSentence = consequenceSentences[0].replace(/[.。]$/, "");
  const actualLoss = lossSentence.replace(/(?:을|를) 잃었습니다$/, "");
  const preserved = consequenceSentences.slice(1).join(". ").replace(/[.。]$/, "") || core.restoration;
  const relationship = core.keyRelationship;

  return {
    protagonistDesire: `${scenario.occupation} 일을 이어가며 지금의 수입과 머물 곳을 지키는 것`,
    keyRelationship: relationship,
    relationshipOrigin: `${withObject(scenario.meetingReason)} 계기로 ${withAnd(relationship)} 처음 같은 문제를 붙들었습니다.`,
    trustReason: `그 뒤에도 약속한 장소와 시간을 지키고 불리한 사실을 감추지 않는 모습을 여러 차례 보았습니다. 그래서 그 사람은 남에게 꺼내지 못한 부탁을 먼저 건넸습니다.`,
    protagonistInvolvement: `${scenario.occupation}인 당신이 ${scenario.signatureObject}과 현장의 사정을 함께 확인할 수 있는 사람이어서, 빠지면 요구를 거절하거나 피해를 막을 사람이 없었습니다.`,
    antagonistMotive: core.secret,
    antagonistInterestInProtagonist: `상대의 계획을 실행하려면 현장을 아는 당신의 확인이나 침묵이 필요했고, 거절하면 감춰 둔 일이 다른 사람들에게 드러날 상황이었습니다.`,
    noEasyExit: `모른 척하면 피해가 눈앞의 사람에게 넘어가고, 반대로 나서면 ${lossSentence}. 직장을 떠나는 것만으로 이미 닥친 피해까지 멈출 수는 없었습니다.`,
    incitingIncident: core.turningPoint,
    firstEscalation: `그날 오후 상대는 요구에 따르지 않으면 일과 머물 곳을 바로 거두겠다고 경고했고, 함께 있던 사람에게 먼저 책임을 씌우려 했습니다.`,
    midpointRevelation: core.secret,
    pointOfNoReturn: core.formalRefusal,
    climax: core.restoration,
    aftermath: core.consequence,
    actualLoss,
    actualGainOrPreservedThing: preserved,
    unspokenWords: `${relationship}에게 이 일을 함께한 뒤로 혼자 돌아가는 길이 전과 같지 않았다고 말하지 못했습니다.`,
    promise: `다시는 같은 일이 한 사람의 침묵에 달리지 않도록 다음 계절에도 함께 확인하겠다는 약속`,
    promiseBreakReason: `${actualLoss} 두 사람은 약속한 장소에서 다시 만나지 못했습니다.`,
    lastVisitor: relationship,
    finalMemory: `${scenario.meetingReason}으로 처음 서로의 손을 빌렸던 날`,
    objectRole,
    dramaticHook: core.dramaticHook,
    decisionActions: {
      ALLY: `${relationship}에게 ${core.truth} 먼저 알리고, 둘이 움직일 순서와 맡을 일을 정했습니다.`,
      TRUTH: `${core.truth} 숨기지 않고 관련된 사람들 앞에서 밝혔습니다.`,
      COMMUNITY: core.collectiveAlternative,
      DEFIANCE: core.formalRefusal,
      DEPARTURE: core.newStart,
      RESTORATION: core.restoration,
    },
    timeline: {
      youth: { title: "일을 배우기 전", summary: `어린 시절부터 ${scenario.region}에서 가족이 맡긴 잔일을 하며 사람과 길을 익혔습니다.`, location: scenario.region },
      earlyAdult: { title: "처음 맡은 자리", summary: scenario.occupationPath, location: scenario.location },
      keyRelationship: { title: "함께 붙든 첫 문제", summary: `${withObject(scenario.meetingReason)} 계기로 ${withAnd(relationship)} 여러 차례 일을 함께했습니다.`, relatedPerson: relationship },
      centralConflict: { title: "거절해야 했던 요구", summary: core.turningPoint, location: scenario.location },
      aftermath: { title: "다음 달의 생활", summary: core.consequence },
      laterLife: { title: "다른 사람에게 건넨 방식", summary: `${core.collectiveAlternative} 이후에는 같은 판단을 혼자 하지 않도록 그 방법을 주변 사람들에게 가르쳤습니다.` },
      finalYears: { title: "다시 온 사람", summary: `말년에는 ${withAnd(relationship)} 다시 만나 ${withObject(scenario.signatureObject)} 사이에 두고 그 뒤 달라진 삶을 이야기했습니다.`, relatedPerson: relationship },
    },
    validation: valid,
  };
}

export function validateLifeBlueprint(blueprint: LifeBlueprint): { success: boolean; errors: string[] } {
  const errors: string[] = [];
  const requiredText: Array<keyof LifeBlueprint> = [
    "protagonistDesire", "keyRelationship", "relationshipOrigin", "trustReason", "protagonistInvolvement",
    "antagonistMotive", "antagonistInterestInProtagonist", "noEasyExit", "incitingIncident", "firstEscalation",
    "midpointRevelation", "pointOfNoReturn", "climax", "aftermath", "actualLoss", "actualGainOrPreservedThing",
  ];
  for (const field of requiredText) {
    if (typeof blueprint[field] !== "string" || blueprint[field].trim().length < 10) errors.push(`${field} is missing`);
  }
  if (Object.values(blueprint.validation).some((value) => !value)) errors.push("causal validation failed");
  if (new Set(Object.values(blueprint.timeline).map((event) => event.summary)).size !== 7) errors.push("timeline events must be distinct");
  return { success: errors.length === 0, errors };
}
